#---基础信息配置---
server:
  port: 8089
  servlet:
    context-path: /marryMacher

#数据库访问配置
#主数据源，默认的
spring:
  mvc:
    static-path-pattern: /**

  datasource:
  #  url: jdbc:mysql://8.133.162.72:3306/matchmaker?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/matchmaker?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  #  password: Aa123456
    password: 123456
  application:
    name: marryMacher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.clb.parkingspace.po
  #  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      db-type: mysql
#      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

    #刷新mapper 调试神器
    refresh: true
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
swagger:
  is:
    enable: true
#日志文件配置
#logging:
#  level:
#   com:
#    clb:
#     parkingspace: debug
#  file: parkingspace.log

#开闸后多久自动关闸时间设置,单位毫秒
lock:
  intervalTime: 30000


#spring:
#  resources:
#    static-locations:
#      resources:
#        static-locations: classpath:/resources/, classpath:/static/ ,classpath:/templates/
#

